# run with "docker compose up -d"
version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.srv
    hostname: "192.168.1.9"
    #container_name: mac-studio.fritz.box IWS_HOST_NAME
    #extra_hosts:
    #  - "host:docker:internal:host-gateway"
    ports:
      - "8091:8091"
    environment:
      - IWS_API_HOST="192.168.1.9"
      - IWS_API_HOST=8091
    volumes:
      - ./iws-data:/Users/iwsmac/datax
    depends_on:
      - db
    #network_mode: "host"
  db:
    image: postgres:15.1-alpine #latest
    restart: always
    volumes:
      - ./postgres-data:/Users/iwsmac/datax
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iws123
      - POSTGRES_DB=iwsN
    hostname: "192.168.1.9"
    ports:
      - "5434:5432"
    command: -p 5432
    #network_mode: host
