# ---- Builder stage ----
FROM ghcr.io/graalvm/native-image-community:24 AS builder

WORKDIR /app

COPY target/scala-3.9.0/iws-api-assembly-*.jar ./iws-api.jar
COPY graal/ ./graal/

RUN native-image \
    --no-fallback \
    -H:+ReportExceptionStackTraces \
    -H:+UnlockExperimentalVMOptions \
    -H:ConfigurationFileDirectories=graal/ \
    -H:IncludeResources=application.conf \
    -H:IncludeResources=reference.conf \
    --enable-url-protocols=http,https \
    --initialize-at-run-time=io.netty.channel.DefaultFileRegion \
    --initialize-at-run-time=io.netty.channel.epoll.Native \
    --initialize-at-run-time=io.netty.channel.epoll.Epoll \
    --initialize-at-run-time=io.netty.channel.epoll.EpollEventLoop \
    --initialize-at-run-time=io.netty.channel.epoll.EpollEventArray \
    --initialize-at-run-time=io.netty.channel.kqueue.KQueue \
    --initialize-at-run-time=io.netty.channel.kqueue.KQueueEventLoop \
    --initialize-at-run-time=io.netty.channel.kqueue.KQueueEventArray \
    --initialize-at-run-time=io.netty.channel.kqueue.Native \
    --initialize-at-run-time=io.netty.channel.unix.Limits \
    --initialize-at-run-time=io.netty.channel.unix.Errors \
    --initialize-at-run-time=io.netty.channel.unix.IovArray \
    --initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils \
    -o /app/iws-api \
    -jar ./iws-api.jar

# ---- Runtime stage ----
FROM gcr.io/distroless/base-debian12

COPY --from=builder /app/iws-api /app/iws-api
COPY --from=builder /usr/lib64/libz.so.1 /lib/aarch64-linux-gnu/libz.so.1

ENTRYPOINT ["/app/iws-api"]
