version: "3.8"
services:
  iws-db:
    image: postgres:latest #15.1-alpine
    restart: always
    tty: true
    networks:
      node-network:
    volumes:
      - ./iws-data-vol:/var/lib/postgresql/data:z
      #- ./sql/create_tables.sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    #network_mode: bridge
    ports:
      - ${POSTGRES_DB_PORT_FROM}:${POSTGRES_DB_PORT_TO}
    container_name: ${IWS_DB_CONTAINER}
  iws-api:
    image: ${IWS_API_IMAGE}:${IWS_API_IMAGE_VERSION}
    restart: always
    tty: true
    networks:
      node-network:
    ports:
      - ${IWS_API_PORT_FROM}:${IWS_API_PORT_TO}
    container_name: ${IWS_API_CONTAINER}
    environment:
      - IWS_API_HOST=${IWS_API_HOST}
      - IWS_API_PORT=${IWS_API_PORT_TO}
      - IWS_WEB_URL=http://${IWS_WEB_HOST}/${IWS_WEB_PORT_TO}
    volumes:
      - ./iws-db-vol:/var/lib/data
    links:
      - "iws-db"
    depends_on:
      - iws-db
  web:
    image: ${IWS_WEB_IMAGE}:${IWS_WEB_IMAGE_VERSION}
    restart: always
    tty: true
    networks:
      node-network:
    ports:
      - ${IWS_WEB_PORT_FROM}:${IWS_WEB_PORT_TO}
    container_name: ${IWS_WEB_CONTAINER}
    environment:
      - NODE_ENV=production
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - REACT_APP_HOST_IP_ADDRESS=${IWS_API_HOST}
      - HOST=${IWS_WEB_PORT_FROM}
      - PORT=${IWS_WEB_PORT_TO}
    #command: bash -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    links:
      - "iws-api"
    depends_on:
      - iws-api
networks:
  node-network:
      driver: bridge